version: "3.9"
services:
    web:
        image: ${DOCKER_REGISTRY-}lab06web
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=http://+:8080
        build: 
            context: .
            dockerfile: Lab06.Web/Dockerfile
        ports:
            - "8080:8080"
        depends_on:
            - sqlserver
    sqlserver:
        image: "mcr.microsoft.com/mssql/server:2019-latest"
        environment:
            MSSQL_SA_PASSWORD: "SuperstrongPass123"
            ACCEPT_EULA: "Y"
            MSSQL_PID: "Express"
        ports:
            - "1450:1433"